//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputAcitons.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputAcitons : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputAcitons()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAcitons"",
    ""maps"": [
        {
            ""name"": ""Locomotion"",
            ""id"": ""13888cae-0fd2-439f-9e9e-242f9def7223"",
            ""actions"": [
                {
                    ""name"": ""Camera Rotate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6d1dbb87-a39a-4b2e-b119-6e0d315e3cec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ca7d7b8d-7208-4dd6-a0e6-4f31a1be12d0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll Or BackStep Or Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""a4775578-e08d-4941-a582-e323e49d8b44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""516499d4-84d2-4db7-bfef-6bc308860f42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""b5ac2abd-ba56-4d0a-bd67-1a41576c5e1b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9743e171-f29c-48e4-b19e-15b077af0f16"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""49482fb6-87c0-49b5-a67a-67ca048626dc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""83b47e38-23e8-4b11-abdf-eb3c76c11bd8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c4326218-c9cb-4c42-b4a1-e0d6adcfcf76"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""360b39a4-a8a9-45e2-8b1a-0093732429d8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll Or BackStep Or Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eb79a04-42d1-460b-907d-0ec5f880eee1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d32bbe2-7735-4f6b-aa38-43d81b5fc2eb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Camera Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Combat"",
            ""id"": ""c5e9d75b-5efd-4673-983b-71e0630f2cde"",
            ""actions"": [
                {
                    ""name"": ""Switch Camera Lock On Mode"",
                    ""type"": ""Button"",
                    ""id"": ""13fdefd6-7fb7-4992-a9bd-b022855432aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look On Target Left One"",
                    ""type"": ""Button"",
                    ""id"": ""20326b44-46df-4dd0-9e0f-e9506cc444cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look On Target Right One"",
                    ""type"": ""Button"",
                    ""id"": ""2ee6fc79-0067-453c-9299-c83aeef35ab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Hold Weapon Mode"",
                    ""type"": ""Button"",
                    ""id"": ""c80433c2-59a4-45cb-a784-b3189816fb1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Comsumable"",
                    ""type"": ""Button"",
                    ""id"": ""b5c51458-5779-4d66-8479-aef69475f513"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Weapon Light Attack Or Shoot Arrow"",
                    ""type"": ""Button"",
                    ""id"": ""aa41a099-9e68-4aa8-b009-739ab2de48d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Critical Attack"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8184a336-9691-48a8-82fc-94fb16e98757"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Weapon Heavy Attack"",
                    ""type"": ""Button"",
                    ""id"": ""45bea139-65c8-41b2-b64c-3123f0b99d34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Weapon Light Attack"",
                    ""type"": ""Button"",
                    ""id"": ""53ee3810-1b78-4560-bb94-29156f40506b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block Or Aim"",
                    ""type"": ""Button"",
                    ""id"": ""b8385f18-638d-483c-afff-94ab18a86144"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Weapon Heavy Attack Or Parry"",
                    ""type"": ""Button"",
                    ""id"": ""b54d8d21-9d85-42f2-a185-5be00122e186"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Right Weapon"",
                    ""type"": ""Button"",
                    ""id"": ""79b87413-8eb6-48da-9cc6-80418309c083"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Left Weapon"",
                    ""type"": ""Button"",
                    ""id"": ""b3cf542f-60dd-42f3-8d09-ef2677c17705"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Spell"",
                    ""type"": ""Button"",
                    ""id"": ""3eef8990-1e0c-4b5b-a56d-e0bc78774cea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch Comsumable"",
                    ""type"": ""Button"",
                    ""id"": ""d29ee335-4ad9-4e71-8a03-c86ec070286f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8f040d23-3666-4d65-bb90-59c52dbc6bae"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Weapon Heavy Attack Or Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5d024be-bd62-4b23-9ec0-3b8eead97eaf"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Hold Weapon Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de1950a0-b0da-4ef9-bd90-c69faa808bed"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Comsumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6f2468d-1226-4e80-beeb-5208fc018d71"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Critical Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53934a0b-139b-4887-b66a-eee726750820"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold(duration=0.4)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Critical Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46b56c0c-dcb2-44c7-a2eb-ed225b9795c9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Weapon Light Attack Or Shoot Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c594b66d-d732-4f74-ba32-d1604609fdf4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Weapon Light Attack Or Shoot Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e35c358-12a7-47c6-80de-5439a5d582f7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Weapon Light Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""423ee83c-f08c-47a5-bb9b-e66ff9141568"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Weapon Light Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfc0440-00ee-454c-9e1f-6a9aa117abe4"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block Or Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71799ee3-f24c-4f2b-a114-855f2bd4bc30"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block Or Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cb6ee6c-9622-495a-b5c4-c632b9769fe2"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Right Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ea6e568-d0b5-4f6b-a4a6-95680d8d11c7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Left Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5c12560-9420-4e7e-a402-8d99e87842c5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Comsumable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c3b75d4-89f7-4536-a1f8-ffbe2520699a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look On Target Right One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f91204f-4216-4508-bd0c-d50c3cb43997"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Camera Lock On Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b16ce72b-ef0f-467e-8103-d36ae512abec"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look On Target Left One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c352d89-ff68-4113-9a46-1d1f6f6170cb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right Weapon Heavy Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""507510bd-bc22-49b7-9e89-d21c2cfcc3f8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Spell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Interacte"",
            ""id"": ""25d99e44-2f51-4022-9f00-cb54cc4426c2"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""4dd71c30-0037-4fa1-bb7d-e0bc41975361"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold"",
                    ""type"": ""Button"",
                    ""id"": ""8eb5c3ea-1193-4bec-bd9d-35a338092e7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""519b3745-7776-4010-a950-7f32a61a32eb"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45adb476-fdde-4b49-8fd1-ade1f93ea822"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Hold(duration=3)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI Switch"",
            ""id"": ""a244fa0c-1abe-4435-8717-c7ff8c14ade4"",
            ""actions"": [
                {
                    ""name"": ""Open Esc Win"",
                    ""type"": ""Button"",
                    ""id"": ""7e461f52-ea7e-44dd-bb7b-4b8c613deb2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab Win Switch"",
                    ""type"": ""Button"",
                    ""id"": ""a591223c-8709-40fe-8e1a-d7190028b469"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bae1d862-c3e7-4234-8209-f88f88e9f34a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Esc Win"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f120b51-a7f6-4f11-b984-ae05b93b483f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab Win Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI Operation"",
            ""id"": ""bc5c3105-294d-4fcc-968e-8d47a8804ab6"",
            ""actions"": [
                {
                    ""name"": ""Move Selector To Left"",
                    ""type"": ""Button"",
                    ""id"": ""f1643e9c-3f73-484a-a2e0-5b331aee17e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Selector To Right"",
                    ""type"": ""Button"",
                    ""id"": ""3c1655ca-ee66-483c-bbcc-591d94dcbd50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Selector To Up"",
                    ""type"": ""Button"",
                    ""id"": ""84cf1435-5a04-47c8-9313-3d1892df675c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move Selector To Down"",
                    ""type"": ""Button"",
                    ""id"": ""2eefa92c-3cb9-46c6-bf21-c958eb4495f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""b0a7731d-f244-4648-93fd-1706b4d5a13e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""ceebfbe9-27b1-4119-84a1-68d3d0b88ce7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ecada616-a980-4bb6-8b3d-e822114cdb57"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf05f6e2-58f5-49db-a1ed-51d6b33bb07f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Selector To Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""074819d5-63ab-47b6-8932-92e0a410d4e5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbad9fdb-2356-48f9-b108-d41399cb68e9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Selector To Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e34e092b-59ae-4e6f-990f-745af0e4d72b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Selector To Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3896d4a6-15d2-4382-8705-a91212530b04"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Selector To Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Locomotion
        m_Locomotion = asset.FindActionMap("Locomotion", throwIfNotFound: true);
        m_Locomotion_CameraRotate = m_Locomotion.FindAction("Camera Rotate", throwIfNotFound: true);
        m_Locomotion_Move = m_Locomotion.FindAction("Move", throwIfNotFound: true);
        m_Locomotion_RollOrBackStepOrSprint = m_Locomotion.FindAction("Roll Or BackStep Or Sprint", throwIfNotFound: true);
        m_Locomotion_Jump = m_Locomotion.FindAction("Jump", throwIfNotFound: true);
        // Combat
        m_Combat = asset.FindActionMap("Combat", throwIfNotFound: true);
        m_Combat_SwitchCameraLockOnMode = m_Combat.FindAction("Switch Camera Lock On Mode", throwIfNotFound: true);
        m_Combat_LookOnTargetLeftOne = m_Combat.FindAction("Look On Target Left One", throwIfNotFound: true);
        m_Combat_LookOnTargetRightOne = m_Combat.FindAction("Look On Target Right One", throwIfNotFound: true);
        m_Combat_SwitchHoldWeaponMode = m_Combat.FindAction("Switch Hold Weapon Mode", throwIfNotFound: true);
        m_Combat_UseComsumable = m_Combat.FindAction("Use Comsumable", throwIfNotFound: true);
        m_Combat_RightWeaponLightAttackOrShootArrow = m_Combat.FindAction("Right Weapon Light Attack Or Shoot Arrow", throwIfNotFound: true);
        m_Combat_CriticalAttack = m_Combat.FindAction("Critical Attack", throwIfNotFound: true);
        m_Combat_RightWeaponHeavyAttack = m_Combat.FindAction("Right Weapon Heavy Attack", throwIfNotFound: true);
        m_Combat_LeftWeaponLightAttack = m_Combat.FindAction("Left Weapon Light Attack", throwIfNotFound: true);
        m_Combat_BlockOrAim = m_Combat.FindAction("Block Or Aim", throwIfNotFound: true);
        m_Combat_LeftWeaponHeavyAttackOrParry = m_Combat.FindAction("Left Weapon Heavy Attack Or Parry", throwIfNotFound: true);
        m_Combat_SwitchRightWeapon = m_Combat.FindAction("Switch Right Weapon", throwIfNotFound: true);
        m_Combat_SwitchLeftWeapon = m_Combat.FindAction("Switch Left Weapon", throwIfNotFound: true);
        m_Combat_SwitchSpell = m_Combat.FindAction("Switch Spell", throwIfNotFound: true);
        m_Combat_SwitchComsumable = m_Combat.FindAction("Switch Comsumable", throwIfNotFound: true);
        // Interacte
        m_Interacte = asset.FindActionMap("Interacte", throwIfNotFound: true);
        m_Interacte_Tap = m_Interacte.FindAction("Tap", throwIfNotFound: true);
        m_Interacte_Hold = m_Interacte.FindAction("Hold", throwIfNotFound: true);
        // UI Switch
        m_UISwitch = asset.FindActionMap("UI Switch", throwIfNotFound: true);
        m_UISwitch_OpenEscWin = m_UISwitch.FindAction("Open Esc Win", throwIfNotFound: true);
        m_UISwitch_TabWinSwitch = m_UISwitch.FindAction("Tab Win Switch", throwIfNotFound: true);
        // UI Operation
        m_UIOperation = asset.FindActionMap("UI Operation", throwIfNotFound: true);
        m_UIOperation_MoveSelectorToLeft = m_UIOperation.FindAction("Move Selector To Left", throwIfNotFound: true);
        m_UIOperation_MoveSelectorToRight = m_UIOperation.FindAction("Move Selector To Right", throwIfNotFound: true);
        m_UIOperation_MoveSelectorToUp = m_UIOperation.FindAction("Move Selector To Up", throwIfNotFound: true);
        m_UIOperation_MoveSelectorToDown = m_UIOperation.FindAction("Move Selector To Down", throwIfNotFound: true);
        m_UIOperation_Back = m_UIOperation.FindAction("Back", throwIfNotFound: true);
        m_UIOperation_Confirm = m_UIOperation.FindAction("Confirm", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Locomotion
    private readonly InputActionMap m_Locomotion;
    private ILocomotionActions m_LocomotionActionsCallbackInterface;
    private readonly InputAction m_Locomotion_CameraRotate;
    private readonly InputAction m_Locomotion_Move;
    private readonly InputAction m_Locomotion_RollOrBackStepOrSprint;
    private readonly InputAction m_Locomotion_Jump;
    public struct LocomotionActions
    {
        private @InputAcitons m_Wrapper;
        public LocomotionActions(@InputAcitons wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraRotate => m_Wrapper.m_Locomotion_CameraRotate;
        public InputAction @Move => m_Wrapper.m_Locomotion_Move;
        public InputAction @RollOrBackStepOrSprint => m_Wrapper.m_Locomotion_RollOrBackStepOrSprint;
        public InputAction @Jump => m_Wrapper.m_Locomotion_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Locomotion; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LocomotionActions set) { return set.Get(); }
        public void SetCallbacks(ILocomotionActions instance)
        {
            if (m_Wrapper.m_LocomotionActionsCallbackInterface != null)
            {
                @CameraRotate.started -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnCameraRotate;
                @CameraRotate.performed -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnCameraRotate;
                @CameraRotate.canceled -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnCameraRotate;
                @Move.started -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnMove;
                @RollOrBackStepOrSprint.started -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnRollOrBackStepOrSprint;
                @RollOrBackStepOrSprint.performed -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnRollOrBackStepOrSprint;
                @RollOrBackStepOrSprint.canceled -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnRollOrBackStepOrSprint;
                @Jump.started -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_LocomotionActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_LocomotionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CameraRotate.started += instance.OnCameraRotate;
                @CameraRotate.performed += instance.OnCameraRotate;
                @CameraRotate.canceled += instance.OnCameraRotate;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RollOrBackStepOrSprint.started += instance.OnRollOrBackStepOrSprint;
                @RollOrBackStepOrSprint.performed += instance.OnRollOrBackStepOrSprint;
                @RollOrBackStepOrSprint.canceled += instance.OnRollOrBackStepOrSprint;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public LocomotionActions @Locomotion => new LocomotionActions(this);

    // Combat
    private readonly InputActionMap m_Combat;
    private ICombatActions m_CombatActionsCallbackInterface;
    private readonly InputAction m_Combat_SwitchCameraLockOnMode;
    private readonly InputAction m_Combat_LookOnTargetLeftOne;
    private readonly InputAction m_Combat_LookOnTargetRightOne;
    private readonly InputAction m_Combat_SwitchHoldWeaponMode;
    private readonly InputAction m_Combat_UseComsumable;
    private readonly InputAction m_Combat_RightWeaponLightAttackOrShootArrow;
    private readonly InputAction m_Combat_CriticalAttack;
    private readonly InputAction m_Combat_RightWeaponHeavyAttack;
    private readonly InputAction m_Combat_LeftWeaponLightAttack;
    private readonly InputAction m_Combat_BlockOrAim;
    private readonly InputAction m_Combat_LeftWeaponHeavyAttackOrParry;
    private readonly InputAction m_Combat_SwitchRightWeapon;
    private readonly InputAction m_Combat_SwitchLeftWeapon;
    private readonly InputAction m_Combat_SwitchSpell;
    private readonly InputAction m_Combat_SwitchComsumable;
    public struct CombatActions
    {
        private @InputAcitons m_Wrapper;
        public CombatActions(@InputAcitons wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchCameraLockOnMode => m_Wrapper.m_Combat_SwitchCameraLockOnMode;
        public InputAction @LookOnTargetLeftOne => m_Wrapper.m_Combat_LookOnTargetLeftOne;
        public InputAction @LookOnTargetRightOne => m_Wrapper.m_Combat_LookOnTargetRightOne;
        public InputAction @SwitchHoldWeaponMode => m_Wrapper.m_Combat_SwitchHoldWeaponMode;
        public InputAction @UseComsumable => m_Wrapper.m_Combat_UseComsumable;
        public InputAction @RightWeaponLightAttackOrShootArrow => m_Wrapper.m_Combat_RightWeaponLightAttackOrShootArrow;
        public InputAction @CriticalAttack => m_Wrapper.m_Combat_CriticalAttack;
        public InputAction @RightWeaponHeavyAttack => m_Wrapper.m_Combat_RightWeaponHeavyAttack;
        public InputAction @LeftWeaponLightAttack => m_Wrapper.m_Combat_LeftWeaponLightAttack;
        public InputAction @BlockOrAim => m_Wrapper.m_Combat_BlockOrAim;
        public InputAction @LeftWeaponHeavyAttackOrParry => m_Wrapper.m_Combat_LeftWeaponHeavyAttackOrParry;
        public InputAction @SwitchRightWeapon => m_Wrapper.m_Combat_SwitchRightWeapon;
        public InputAction @SwitchLeftWeapon => m_Wrapper.m_Combat_SwitchLeftWeapon;
        public InputAction @SwitchSpell => m_Wrapper.m_Combat_SwitchSpell;
        public InputAction @SwitchComsumable => m_Wrapper.m_Combat_SwitchComsumable;
        public InputActionMap Get() { return m_Wrapper.m_Combat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CombatActions set) { return set.Get(); }
        public void SetCallbacks(ICombatActions instance)
        {
            if (m_Wrapper.m_CombatActionsCallbackInterface != null)
            {
                @SwitchCameraLockOnMode.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchCameraLockOnMode;
                @SwitchCameraLockOnMode.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchCameraLockOnMode;
                @SwitchCameraLockOnMode.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchCameraLockOnMode;
                @LookOnTargetLeftOne.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetLeftOne;
                @LookOnTargetLeftOne.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetLeftOne;
                @LookOnTargetLeftOne.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetLeftOne;
                @LookOnTargetRightOne.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetRightOne;
                @LookOnTargetRightOne.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetRightOne;
                @LookOnTargetRightOne.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnLookOnTargetRightOne;
                @SwitchHoldWeaponMode.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchHoldWeaponMode;
                @SwitchHoldWeaponMode.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchHoldWeaponMode;
                @SwitchHoldWeaponMode.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchHoldWeaponMode;
                @UseComsumable.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnUseComsumable;
                @UseComsumable.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnUseComsumable;
                @UseComsumable.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnUseComsumable;
                @RightWeaponLightAttackOrShootArrow.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponLightAttackOrShootArrow;
                @RightWeaponLightAttackOrShootArrow.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponLightAttackOrShootArrow;
                @RightWeaponLightAttackOrShootArrow.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponLightAttackOrShootArrow;
                @CriticalAttack.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnCriticalAttack;
                @CriticalAttack.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnCriticalAttack;
                @CriticalAttack.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnCriticalAttack;
                @RightWeaponHeavyAttack.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponHeavyAttack;
                @RightWeaponHeavyAttack.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponHeavyAttack;
                @RightWeaponHeavyAttack.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnRightWeaponHeavyAttack;
                @LeftWeaponLightAttack.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponLightAttack;
                @LeftWeaponLightAttack.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponLightAttack;
                @LeftWeaponLightAttack.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponLightAttack;
                @BlockOrAim.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnBlockOrAim;
                @BlockOrAim.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnBlockOrAim;
                @BlockOrAim.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnBlockOrAim;
                @LeftWeaponHeavyAttackOrParry.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponHeavyAttackOrParry;
                @LeftWeaponHeavyAttackOrParry.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponHeavyAttackOrParry;
                @LeftWeaponHeavyAttackOrParry.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnLeftWeaponHeavyAttackOrParry;
                @SwitchRightWeapon.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchRightWeapon;
                @SwitchRightWeapon.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchRightWeapon;
                @SwitchRightWeapon.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchRightWeapon;
                @SwitchLeftWeapon.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchLeftWeapon;
                @SwitchLeftWeapon.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchLeftWeapon;
                @SwitchLeftWeapon.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchLeftWeapon;
                @SwitchSpell.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchSpell;
                @SwitchSpell.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchSpell;
                @SwitchSpell.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchSpell;
                @SwitchComsumable.started -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchComsumable;
                @SwitchComsumable.performed -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchComsumable;
                @SwitchComsumable.canceled -= m_Wrapper.m_CombatActionsCallbackInterface.OnSwitchComsumable;
            }
            m_Wrapper.m_CombatActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwitchCameraLockOnMode.started += instance.OnSwitchCameraLockOnMode;
                @SwitchCameraLockOnMode.performed += instance.OnSwitchCameraLockOnMode;
                @SwitchCameraLockOnMode.canceled += instance.OnSwitchCameraLockOnMode;
                @LookOnTargetLeftOne.started += instance.OnLookOnTargetLeftOne;
                @LookOnTargetLeftOne.performed += instance.OnLookOnTargetLeftOne;
                @LookOnTargetLeftOne.canceled += instance.OnLookOnTargetLeftOne;
                @LookOnTargetRightOne.started += instance.OnLookOnTargetRightOne;
                @LookOnTargetRightOne.performed += instance.OnLookOnTargetRightOne;
                @LookOnTargetRightOne.canceled += instance.OnLookOnTargetRightOne;
                @SwitchHoldWeaponMode.started += instance.OnSwitchHoldWeaponMode;
                @SwitchHoldWeaponMode.performed += instance.OnSwitchHoldWeaponMode;
                @SwitchHoldWeaponMode.canceled += instance.OnSwitchHoldWeaponMode;
                @UseComsumable.started += instance.OnUseComsumable;
                @UseComsumable.performed += instance.OnUseComsumable;
                @UseComsumable.canceled += instance.OnUseComsumable;
                @RightWeaponLightAttackOrShootArrow.started += instance.OnRightWeaponLightAttackOrShootArrow;
                @RightWeaponLightAttackOrShootArrow.performed += instance.OnRightWeaponLightAttackOrShootArrow;
                @RightWeaponLightAttackOrShootArrow.canceled += instance.OnRightWeaponLightAttackOrShootArrow;
                @CriticalAttack.started += instance.OnCriticalAttack;
                @CriticalAttack.performed += instance.OnCriticalAttack;
                @CriticalAttack.canceled += instance.OnCriticalAttack;
                @RightWeaponHeavyAttack.started += instance.OnRightWeaponHeavyAttack;
                @RightWeaponHeavyAttack.performed += instance.OnRightWeaponHeavyAttack;
                @RightWeaponHeavyAttack.canceled += instance.OnRightWeaponHeavyAttack;
                @LeftWeaponLightAttack.started += instance.OnLeftWeaponLightAttack;
                @LeftWeaponLightAttack.performed += instance.OnLeftWeaponLightAttack;
                @LeftWeaponLightAttack.canceled += instance.OnLeftWeaponLightAttack;
                @BlockOrAim.started += instance.OnBlockOrAim;
                @BlockOrAim.performed += instance.OnBlockOrAim;
                @BlockOrAim.canceled += instance.OnBlockOrAim;
                @LeftWeaponHeavyAttackOrParry.started += instance.OnLeftWeaponHeavyAttackOrParry;
                @LeftWeaponHeavyAttackOrParry.performed += instance.OnLeftWeaponHeavyAttackOrParry;
                @LeftWeaponHeavyAttackOrParry.canceled += instance.OnLeftWeaponHeavyAttackOrParry;
                @SwitchRightWeapon.started += instance.OnSwitchRightWeapon;
                @SwitchRightWeapon.performed += instance.OnSwitchRightWeapon;
                @SwitchRightWeapon.canceled += instance.OnSwitchRightWeapon;
                @SwitchLeftWeapon.started += instance.OnSwitchLeftWeapon;
                @SwitchLeftWeapon.performed += instance.OnSwitchLeftWeapon;
                @SwitchLeftWeapon.canceled += instance.OnSwitchLeftWeapon;
                @SwitchSpell.started += instance.OnSwitchSpell;
                @SwitchSpell.performed += instance.OnSwitchSpell;
                @SwitchSpell.canceled += instance.OnSwitchSpell;
                @SwitchComsumable.started += instance.OnSwitchComsumable;
                @SwitchComsumable.performed += instance.OnSwitchComsumable;
                @SwitchComsumable.canceled += instance.OnSwitchComsumable;
            }
        }
    }
    public CombatActions @Combat => new CombatActions(this);

    // Interacte
    private readonly InputActionMap m_Interacte;
    private IInteracteActions m_InteracteActionsCallbackInterface;
    private readonly InputAction m_Interacte_Tap;
    private readonly InputAction m_Interacte_Hold;
    public struct InteracteActions
    {
        private @InputAcitons m_Wrapper;
        public InteracteActions(@InputAcitons wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_Interacte_Tap;
        public InputAction @Hold => m_Wrapper.m_Interacte_Hold;
        public InputActionMap Get() { return m_Wrapper.m_Interacte; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteracteActions set) { return set.Get(); }
        public void SetCallbacks(IInteracteActions instance)
        {
            if (m_Wrapper.m_InteracteActionsCallbackInterface != null)
            {
                @Tap.started -= m_Wrapper.m_InteracteActionsCallbackInterface.OnTap;
                @Tap.performed -= m_Wrapper.m_InteracteActionsCallbackInterface.OnTap;
                @Tap.canceled -= m_Wrapper.m_InteracteActionsCallbackInterface.OnTap;
                @Hold.started -= m_Wrapper.m_InteracteActionsCallbackInterface.OnHold;
                @Hold.performed -= m_Wrapper.m_InteracteActionsCallbackInterface.OnHold;
                @Hold.canceled -= m_Wrapper.m_InteracteActionsCallbackInterface.OnHold;
            }
            m_Wrapper.m_InteracteActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Tap.started += instance.OnTap;
                @Tap.performed += instance.OnTap;
                @Tap.canceled += instance.OnTap;
                @Hold.started += instance.OnHold;
                @Hold.performed += instance.OnHold;
                @Hold.canceled += instance.OnHold;
            }
        }
    }
    public InteracteActions @Interacte => new InteracteActions(this);

    // UI Switch
    private readonly InputActionMap m_UISwitch;
    private IUISwitchActions m_UISwitchActionsCallbackInterface;
    private readonly InputAction m_UISwitch_OpenEscWin;
    private readonly InputAction m_UISwitch_TabWinSwitch;
    public struct UISwitchActions
    {
        private @InputAcitons m_Wrapper;
        public UISwitchActions(@InputAcitons wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenEscWin => m_Wrapper.m_UISwitch_OpenEscWin;
        public InputAction @TabWinSwitch => m_Wrapper.m_UISwitch_TabWinSwitch;
        public InputActionMap Get() { return m_Wrapper.m_UISwitch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UISwitchActions set) { return set.Get(); }
        public void SetCallbacks(IUISwitchActions instance)
        {
            if (m_Wrapper.m_UISwitchActionsCallbackInterface != null)
            {
                @OpenEscWin.started -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnOpenEscWin;
                @OpenEscWin.performed -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnOpenEscWin;
                @OpenEscWin.canceled -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnOpenEscWin;
                @TabWinSwitch.started -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnTabWinSwitch;
                @TabWinSwitch.performed -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnTabWinSwitch;
                @TabWinSwitch.canceled -= m_Wrapper.m_UISwitchActionsCallbackInterface.OnTabWinSwitch;
            }
            m_Wrapper.m_UISwitchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenEscWin.started += instance.OnOpenEscWin;
                @OpenEscWin.performed += instance.OnOpenEscWin;
                @OpenEscWin.canceled += instance.OnOpenEscWin;
                @TabWinSwitch.started += instance.OnTabWinSwitch;
                @TabWinSwitch.performed += instance.OnTabWinSwitch;
                @TabWinSwitch.canceled += instance.OnTabWinSwitch;
            }
        }
    }
    public UISwitchActions @UISwitch => new UISwitchActions(this);

    // UI Operation
    private readonly InputActionMap m_UIOperation;
    private IUIOperationActions m_UIOperationActionsCallbackInterface;
    private readonly InputAction m_UIOperation_MoveSelectorToLeft;
    private readonly InputAction m_UIOperation_MoveSelectorToRight;
    private readonly InputAction m_UIOperation_MoveSelectorToUp;
    private readonly InputAction m_UIOperation_MoveSelectorToDown;
    private readonly InputAction m_UIOperation_Back;
    private readonly InputAction m_UIOperation_Confirm;
    public struct UIOperationActions
    {
        private @InputAcitons m_Wrapper;
        public UIOperationActions(@InputAcitons wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveSelectorToLeft => m_Wrapper.m_UIOperation_MoveSelectorToLeft;
        public InputAction @MoveSelectorToRight => m_Wrapper.m_UIOperation_MoveSelectorToRight;
        public InputAction @MoveSelectorToUp => m_Wrapper.m_UIOperation_MoveSelectorToUp;
        public InputAction @MoveSelectorToDown => m_Wrapper.m_UIOperation_MoveSelectorToDown;
        public InputAction @Back => m_Wrapper.m_UIOperation_Back;
        public InputAction @Confirm => m_Wrapper.m_UIOperation_Confirm;
        public InputActionMap Get() { return m_Wrapper.m_UIOperation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIOperationActions set) { return set.Get(); }
        public void SetCallbacks(IUIOperationActions instance)
        {
            if (m_Wrapper.m_UIOperationActionsCallbackInterface != null)
            {
                @MoveSelectorToLeft.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToLeft;
                @MoveSelectorToLeft.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToLeft;
                @MoveSelectorToLeft.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToLeft;
                @MoveSelectorToRight.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToRight;
                @MoveSelectorToRight.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToRight;
                @MoveSelectorToRight.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToRight;
                @MoveSelectorToUp.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToUp;
                @MoveSelectorToUp.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToUp;
                @MoveSelectorToUp.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToUp;
                @MoveSelectorToDown.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToDown;
                @MoveSelectorToDown.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToDown;
                @MoveSelectorToDown.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnMoveSelectorToDown;
                @Back.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnBack;
                @Confirm.started -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_UIOperationActionsCallbackInterface.OnConfirm;
            }
            m_Wrapper.m_UIOperationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveSelectorToLeft.started += instance.OnMoveSelectorToLeft;
                @MoveSelectorToLeft.performed += instance.OnMoveSelectorToLeft;
                @MoveSelectorToLeft.canceled += instance.OnMoveSelectorToLeft;
                @MoveSelectorToRight.started += instance.OnMoveSelectorToRight;
                @MoveSelectorToRight.performed += instance.OnMoveSelectorToRight;
                @MoveSelectorToRight.canceled += instance.OnMoveSelectorToRight;
                @MoveSelectorToUp.started += instance.OnMoveSelectorToUp;
                @MoveSelectorToUp.performed += instance.OnMoveSelectorToUp;
                @MoveSelectorToUp.canceled += instance.OnMoveSelectorToUp;
                @MoveSelectorToDown.started += instance.OnMoveSelectorToDown;
                @MoveSelectorToDown.performed += instance.OnMoveSelectorToDown;
                @MoveSelectorToDown.canceled += instance.OnMoveSelectorToDown;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
            }
        }
    }
    public UIOperationActions @UIOperation => new UIOperationActions(this);
    public interface ILocomotionActions
    {
        void OnCameraRotate(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnRollOrBackStepOrSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface ICombatActions
    {
        void OnSwitchCameraLockOnMode(InputAction.CallbackContext context);
        void OnLookOnTargetLeftOne(InputAction.CallbackContext context);
        void OnLookOnTargetRightOne(InputAction.CallbackContext context);
        void OnSwitchHoldWeaponMode(InputAction.CallbackContext context);
        void OnUseComsumable(InputAction.CallbackContext context);
        void OnRightWeaponLightAttackOrShootArrow(InputAction.CallbackContext context);
        void OnCriticalAttack(InputAction.CallbackContext context);
        void OnRightWeaponHeavyAttack(InputAction.CallbackContext context);
        void OnLeftWeaponLightAttack(InputAction.CallbackContext context);
        void OnBlockOrAim(InputAction.CallbackContext context);
        void OnLeftWeaponHeavyAttackOrParry(InputAction.CallbackContext context);
        void OnSwitchRightWeapon(InputAction.CallbackContext context);
        void OnSwitchLeftWeapon(InputAction.CallbackContext context);
        void OnSwitchSpell(InputAction.CallbackContext context);
        void OnSwitchComsumable(InputAction.CallbackContext context);
    }
    public interface IInteracteActions
    {
        void OnTap(InputAction.CallbackContext context);
        void OnHold(InputAction.CallbackContext context);
    }
    public interface IUISwitchActions
    {
        void OnOpenEscWin(InputAction.CallbackContext context);
        void OnTabWinSwitch(InputAction.CallbackContext context);
    }
    public interface IUIOperationActions
    {
        void OnMoveSelectorToLeft(InputAction.CallbackContext context);
        void OnMoveSelectorToRight(InputAction.CallbackContext context);
        void OnMoveSelectorToUp(InputAction.CallbackContext context);
        void OnMoveSelectorToDown(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
    }
}
